trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - src/*
      - Dockerfile
      - azure-pipelines.yml

pr:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: common-variables
  - name: dockerRegistryServiceConnection
    value: 'acr-connection'
  - name: imageRepository
    value: 'demo-app'
  - name: containerRegistry
    value: 'myregistry.azurecr.io'
  - name: dockerfilePath
    value: '$(Build.SourcesDirectory)/Dockerfile'
  - name: tag
    value: '$(Build.BuildId)'
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

stages:
  - stage: Build
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: BuildJob
        displayName: 'Build Docker Image'
        steps:
          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: build
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest
              arguments: '--build-arg BUILD_DATE=$(Build.BuildId) --build-arg VERSION=$(tag)'

          - task: Docker@2
            displayName: 'Scan Docker Image'
            inputs:
              command: run
              arguments: '--rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image --severity HIGH,CRITICAL $(imageRepository):$(tag)'
            continueOnError: true

          - task: Docker@2
            displayName: 'Push Docker Image to ACR'
            condition: and(succeeded(), eq(variables.isMain, true))
            inputs:
              command: push
              repository: $(imageRepository)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Kubernetes Manifests'
            inputs:
              targetPath: '$(Build.SourcesDirectory)/k8s'
              artifact: 'k8s-manifests'
              publishLocation: 'pipeline'

  - stage: DeployDev
    displayName: 'Deploy to Development'
    dependsOn: Build
    condition: and(succeeded(), eq(variables.isMain, true))
    variables:
      - group: dev-variables
    jobs:
      - deployment: DeployToDev
        displayName: 'Deploy to Dev AKS'
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  displayName: 'Download K8s Manifests'
                  inputs:
                    artifact: 'k8s-manifests'
                    path: '$(Pipeline.Workspace)/k8s'

                - task: KubernetesManifest@0
                  displayName: 'Deploy to AKS'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'aks-dev-connection'
                    namespace: 'demo-app-dev'
                    manifests: |
                      $(Pipeline.Workspace)/k8s/deployment.yaml
                      $(Pipeline.Workspace)/k8s/service.yaml
                      $(Pipeline.Workspace)/k8s/ingress.yaml
                    containers: '$(containerRegistry)/$(imageRepository):$(tag)'

                - task: KubernetesManifest@0
                  displayName: 'Check Deployment Status'
                  inputs:
                    action: 'get'
                    kubernetesServiceConnection: 'aks-dev-connection'
                    namespace: 'demo-app-dev'
                    arguments: 'deployments'

  - stage: DeployProd
    displayName: 'Deploy to Production'
    dependsOn: DeployDev
    condition: and(succeeded(), eq(variables.isMain, true))
    variables:
      - group: prod-variables
    jobs:
      - deployment: DeployToProd
        displayName: 'Deploy to Prod AKS'
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  displayName: 'Download K8s Manifests'
                  inputs:
                    artifact: 'k8s-manifests'
                    path: '$(Pipeline.Workspace)/k8s'

                - task: KubernetesManifest@0
                  displayName: 'Deploy to AKS'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'aks-prod-connection'
                    namespace: 'demo-app-prod'
                    manifests: |
                      $(Pipeline.Workspace)/k8s/deployment.yaml
                      $(Pipeline.Workspace)/k8s/service.yaml
                      $(Pipeline.Workspace)/k8s/ingress.yaml
                    containers: '$(containerRegistry)/$(imageRepository):$(tag)'

                - task: Bash@3
                  displayName: 'Health Check'
                  inputs:
                    targetType: 'inline'
                    script: |
                      echo "Performing health check..."
                      sleep 30
                      # Add actual health check logic here
                      echo "Health check passed"

                - task: Bash@3
                  displayName: 'Send Deployment Notification'
                  inputs:
                    targetType: 'inline'
                    script: |
                      echo "Deployment to production completed successfully"
                      echo "Image: $(containerRegistry)/$(imageRepository):$(tag)"
