trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - src/*
      - package.json
      - azure-pipelines.yml

pr:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: nodejs-variables
  - name: nodeVersion
    value: '20.x'
  - name: npmCache
    value: '$(Pipeline.Workspace)/.npm'

stages:
  - stage: Build
    displayName: 'Build and Test'
    jobs:
      - job: BuildJob
        displayName: 'Build Node.js Application'
        steps:
          - task: NodeTool@0
            displayName: 'Use Node.js $(nodeVersion)'
            inputs:
              versionSpec: $(nodeVersion)

          - task: Cache@2
            displayName: 'Cache npm packages'
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
                npm
              path: $(npmCache)

          - task: Npm@1
            displayName: 'npm install'
            inputs:
              command: 'ci'
              workingDir: '$(System.DefaultWorkingDirectory)'
              verbose: false
            env:
              npm_config_cache: $(npmCache)

          - task: Npm@1
            displayName: 'npm run lint'
            inputs:
              command: 'custom'
              workingDir: '$(System.DefaultWorkingDirectory)'
              customCommand: 'run lint'
            continueOnError: true

          - task: Npm@1
            displayName: 'npm run test'
            inputs:
              command: 'custom'
              workingDir: '$(System.DefaultWorkingDirectory)'
              customCommand: 'run test -- --coverage --ci'

          - task: PublishCodeCoverageResults@1
            displayName: 'Publish Code Coverage'
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
              reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'

          - task: PublishTestResults@2
            displayName: 'Publish Test Results'
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/test-results.xml'
              failTaskOnFailedTests: true

          - task: Npm@1
            displayName: 'npm run build'
            inputs:
              command: 'custom'
              workingDir: '$(System.DefaultWorkingDirectory)'
              customCommand: 'run build'

          - task: ArchiveFiles@2
            displayName: 'Archive Application'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Artifact'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifact: 'drop'
              publishLocation: 'pipeline'

  - stage: BuildDocker
    displayName: 'Build Docker Image'
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: DockerBuild
        displayName: 'Build and Push Docker Image'
        steps:
          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: 'build'
              repository: 'demo-nodejs-app'
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              containerRegistry: 'acr-connection'
              tags: |
                $(Build.BuildId)
                latest

          - task: Docker@2
            displayName: 'Push Docker Image'
            inputs:
              command: 'push'
              repository: 'demo-nodejs-app'
              containerRegistry: 'acr-connection'
              tags: |
                $(Build.BuildId)
                latest

  - stage: DeployDev
    displayName: 'Deploy to Development'
    dependsOn: BuildDocker
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      - group: dev-environment
    jobs:
      - deployment: DeployDev
        displayName: 'Deploy to Dev Environment'
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy to Azure Web App'
                  inputs:
                    azureSubscription: 'azure-subscription'
                    appName: '$(webAppName)-dev'
                    containers: '$(containerRegistry)/demo-nodejs-app:$(Build.BuildId)'

                - task: Bash@3
                  displayName: 'Smoke Test'
                  inputs:
                    targetType: 'inline'
                    script: |
                      echo "Running smoke tests..."
                      sleep 10
                      curl -f https://$(webAppName)-dev.azurewebsites.net/health || exit 1
                      echo "Smoke tests passed"

  - stage: DeployProd
    displayName: 'Deploy to Production'
    dependsOn: DeployDev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      - group: prod-environment
    jobs:
      - deployment: DeployProd
        displayName: 'Deploy to Production Environment'
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy to Azure Web App'
                  inputs:
                    azureSubscription: 'azure-subscription'
                    appName: '$(webAppName)-prod'
                    containers: '$(containerRegistry)/demo-nodejs-app:$(Build.BuildId)'

                - task: Bash@3
                  displayName: 'Health Check'
                  inputs:
                    targetType: 'inline'
                    script: |
                      echo "Performing health check..."
                      sleep 30
                      for i in {1..5}; do
                        if curl -f https://$(webAppName)-prod.azurewebsites.net/health; then
                          echo "Health check passed"
                          exit 0
                        fi
                        echo "Attempt $i failed, retrying..."
                        sleep 10
                      done
                      echo "Health check failed"
                      exit 1
